{% set name = "pytensor-distributions" %}
{% set version = "0.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 05f34156fb4b63ded816a01f39fe85ed93160b2a2ffcf5d78a32954fa74535fb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<312]

requirements:
  host:
    - pip
    - python
    - flit-core >=3.4,<4
  run:
    - python
    - numpy >=2.0
    - pytensor >=3.0.0,<4.0.0

test:
  imports:
    - pytensor_distributions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pymc-devs/pytensor-distributions
  summary: PyTensor powered distributions.
  description: |
    Probability distributions implemented on top of PyTensor for use in PyMC and
    related libraries.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://pytensor-distributions.readthedocs.io/
  dev_url: https://github.com/pymc-devs/pytensor-distributions

extra:
  recipe-maintainers:
    - aloctavodia
    - ricardov94
    - maresb
